### ISSUE TITLE
Not compatible with the newest format from Sunbreak

### ISSUE THREAD

**Issue by gradashy** [Silvris/MDF-Manager#1]
Not exactly an issue but the new format added on Sunbreak is not compatible.

**Comment by Sephodious** [comment]
Confirm.  New files are mdf2.23

Changing it to .19 for loading in MDF-Manager might work but regardless after Sunbreak it no longer reads mdf2 files by default.

**Comment by Marchs08** [comment]
mdf2.23 version is not release  >.<

**Comment by Sephodious** [comment]
This program still works to edit .23 files.

Make a copy of the mdf2.23 file and rename it to .19

Open with this program.

Edit to your liking and then save

Rename back to .23 

Profit.
